notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/install-swift.sh)"
script: 
  - swift build
  - swift build -c release
  - swift test
